//package com.exavalu.fleetmanagementapp.repositories;
//
//import com.exavalu.fleetmanagementapp.models.Forms;
//import org.springframework.data.jpa.repository.JpaRepository;
//import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
//import org.springframework.data.querydsl.QuerydslPredicateExecutor;
//import org.springframework.stereotype.Repository;
//
///**
//* Generated by Spring Data Generator on 13/06/2024
//*/
//@Repository
//public interface FormsRepository extends JpaRepository<Forms, Integer>, JpaSpecificationExecutor<Forms>, QuerydslPredicateExecutor<Forms> {
//
//}
