package com.exavalu.fleetmanagementapp.repositories;

import com.exavalu.fleetmanagementapp.models.Inspections;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 13/06/2024
*/
@Repository
public interface InspectionsRepository extends JpaRepository<Inspections, Integer>, JpaSpecificationExecutor<Inspections> {

}
